# Generated by Django 5.2.16 on 2026-08-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweet", "0006_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="tweet",
        ),
    ]
